version: '2.2'

services:
  app:
    build:
      context: .
      dockerfile: ./.config/prod/Dockerfile
    container_name: web
    ports:
      - '8000:8000'
    command: uvicorn main.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: .
      dockerfile: ./.config/prod/Dockerfile
    command: "celery -A main worker -l info"
    volumes: 
      - ./:/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
  celery_beat:
    build:
      context: .
      dockerfile: ./.config/prod/Dockerfile
    command: "celery -A main beat -l info"
    volumes: 
      - ./:/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  redis_data:
