# Generated by Django 4.1.2 on 2024-01-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('title', models.CharField(default='', max_length=256, verbose_name='제목')),
                ('esg_category', models.CharField(default='', max_length=256, verbose_name='ESG 항목 구분')),
                ('level_classification', models.CharField(default='', max_length=256, verbose_name='기초/심화 구분')),
                ('code', models.CharField(default='', max_length=256, verbose_name='코드')),
                ('description', models.TextField(verbose_name='설명')),
                ('performance_review', models.TextField(verbose_name='성과점검')),
                ('remark', models.CharField(default='', max_length=256, verbose_name='비고')),
            ],
            options={
                'verbose_name': '평가표',
                'db_table': 'score_card',
            },
        ),
        migrations.CreateModel(
            name='EvaluationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('evaluation_content', models.CharField(default='', max_length=64, verbose_name='평가내용')),
                ('evaluation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='평가점수')),
                ('score_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.scorecard', verbose_name='평가표')),
            ],
            options={
                'verbose_name': '평가 데이터',
                'db_table': 'evaluation_data',
            },
        ),
    ]
