# Generated by Django 4.1.2 on 2024-01-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('esg_category', models.CharField(default='', max_length=256, verbose_name='ESG 항목 구분')),
                ('classification_value', models.CharField(default='', max_length=256, verbose_name='중분류 값')),
                ('description', models.TextField(verbose_name='설명')),
            ],
            options={
                'verbose_name': '평가표 분류값',
                'db_table': 'category',
            },
        ),
    ]
