# Generated by Django 4.1.2 on 2024-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='middle_classification',
            field=models.CharField(default='', max_length=256, verbose_name='중분류 값'),
        ),
    ]
