# Generated by Django 4.1.2 on 2024-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_scorecard_middle_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='middle_classification_description',
            field=models.CharField(default='', max_length=256, verbose_name='중분류 설명 값'),
        ),
    ]
