# Generated by Django 4.1.2 on 2024-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_scorecard_middle_classification_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardInformationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('ranking', models.CharField(default='', max_length=256, verbose_name='랭킹')),
            ],
            options={
                'verbose_name': '기준정보 키워드',
                'db_table': 'standard_information_keyword',
            },
        ),
        migrations.CreateModel(
            name='StandardInformationURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('url', models.CharField(default='', max_length=256, verbose_name='url')),
                ('product', models.CharField(default='', max_length=256, verbose_name='제품')),
                ('conversion_keyword', models.CharField(default='', max_length=256, verbose_name='전환 키워드')),
                ('manuscript_form', models.CharField(default='', max_length=256, verbose_name='원고 형태')),
                ('publication_keyword', models.CharField(default='', max_length=256, verbose_name='발행 키워드')),
            ],
            options={
                'verbose_name': '기준정보 URL',
                'db_table': 'standard_information_url',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EvaluationData',
        ),
        migrations.DeleteModel(
            name='ScoreCard',
        ),
    ]
