# Generated by Django 4.1.2 on 2024-03-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_standardinformationkeyword_standardinformationurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardinformationkeyword',
            name='ranking',
        ),
        migrations.AddField(
            model_name='standardinformationkeyword',
            name='priority',
            field=models.CharField(default='', max_length=256, verbose_name='우선순위'),
        ),
        migrations.CreateModel(
            name='DailyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('autocomplete_keyword', models.CharField(default='', max_length=256, verbose_name='자동완성 키워드')),
                ('pc_views', models.IntegerField(default=0, verbose_name='조회수(PC)')),
                ('mobile_views', models.IntegerField(default=0, verbose_name='조회수(Mobile)')),
                ('area_ranking', models.IntegerField(default=0, verbose_name='영역 순위')),
                ('ranking', models.IntegerField(default=0, verbose_name='순위')),
                ('name', models.CharField(default='', max_length=256, verbose_name='ID(답변인 이름)')),
                ('is_transmission', models.BooleanField(default=False, verbose_name='송출 유무')),
                ('question_date', models.DateTimeField(verbose_name='질문일자')),
                ('type', models.CharField(default='', max_length=256, verbose_name='종류')),
                ('is_subkeyword', models.BooleanField(default=False, verbose_name='서브키워드 유무')),
                ('standard_information_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.standardinformationkeyword', verbose_name='기준정보 키워드')),
                ('standard_information_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.standardinformationurl', verbose_name='기준정보 URL')),
            ],
            options={
                'verbose_name': '일일 결과',
                'db_table': 'daily_result',
            },
        ),
    ]
