# Generated by Django 4.1.2 on 2024-03-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_standardinformationkeyword_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='standard_information_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.standardinformationurl', verbose_name='기준정보 URL'),
        ),
    ]
