# Generated by Django 4.1.2 on 2024-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_dailyresult_standard_information_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='question_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='질문일자'),
        ),
    ]
