# Generated by Django 4.1.2 on 2024-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_dailyresult_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='question_date',
            field=models.CharField(default='', max_length=256, verbose_name='질문일자'),
        ),
    ]
