# Generated by Django 4.1.2 on 2024-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_dailyresult_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='last_crawl_location',
            field=models.BooleanField(default=True, verbose_name='마지막 크롤링 위치'),
        ),
    ]
