# Generated by Django 4.1.2 on 2024-03-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_dailyresult_last_crawl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProcessedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('last_processed_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'last_processed_index',
            },
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='last_crawl_location',
        ),
    ]
