# Generated by Django 4.1.2 on 2024-03-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_lastprocessedindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('ip', models.CharField(max_length=256, verbose_name='403 IP')),
            ],
            options={
                'db_table': 'block_ip',
            },
        ),
    ]
