# Generated by Django 4.1.2 on 2024-03-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_blockip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresult',
            name='autocomplete_keyword',
        ),
    ]
