# Generated by Django 4.1.2 on 2024-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_remove_dailyresult_autocomplete_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyresult',
            name='mobile_views',
            field=models.CharField(default='', max_length=256, verbose_name='조회수(Mobile)'),
        ),
        migrations.AlterField(
            model_name='dailyresult',
            name='pc_views',
            field=models.CharField(default='', max_length=256, verbose_name='조회수(PC)'),
        ),
    ]
