# Generated by Django 4.1.2 on 2024-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_dailyresult_mobile_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_lock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '일일 수집 유무 확인',
                'verbose_name_plural': '일일 수집 유무 확인',
                'db_table': 'check_collection',
            },
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='standard_information_keyword',
        ),
        migrations.RemoveField(
            model_name='dailyresult',
            name='standard_information_url',
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='conversion_keyword',
            field=models.CharField(default='', max_length=256, verbose_name='전환 키워드'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='keyword',
            field=models.CharField(default='', max_length=256, verbose_name='키워드'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='keyword_product',
            field=models.CharField(default='', max_length=256, verbose_name='제품(키워드 파일)'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='manuscript_form',
            field=models.CharField(default='', max_length=256, verbose_name='원고 형태'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='priority',
            field=models.CharField(default='', max_length=256, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='publication_keyword',
            field=models.CharField(default='', max_length=256, verbose_name='발행 키워드'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='url',
            field=models.CharField(default='', max_length=256, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='url_product',
            field=models.CharField(default='', max_length=256, verbose_name='제품(URL 파일)'),
        ),
        migrations.AddField(
            model_name='standardinformationkeyword',
            name='product',
            field=models.CharField(default='', max_length=256, verbose_name='제품'),
        ),
    ]
