# Generated by Django 4.1.2 on 2024-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_checkcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyresult',
            name='transmission_url_comment_cnt',
            field=models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 조회수'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='transmission_url_date',
            field=models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 작성일'),
        ),
        migrations.AddField(
            model_name='dailyresult',
            name='transmission_url_views',
            field=models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 조회수'),
        ),
    ]
