# Generated by Django 4.1.2 on 2024-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_dailyresult_transmission_url_comment_cnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesttDailyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('keyword_product', models.CharField(default='', max_length=256, verbose_name='제품(키워드 파일)')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('priority', models.CharField(default='', max_length=256, verbose_name='우선순위')),
                ('url', models.CharField(default='', max_length=256, verbose_name='url')),
                ('url_product', models.CharField(default='', max_length=256, verbose_name='제품(URL 파일)')),
                ('conversion_keyword', models.CharField(default='', max_length=256, verbose_name='전환 키워드')),
                ('manuscript_form', models.CharField(default='', max_length=256, verbose_name='원고 형태')),
                ('publication_keyword', models.CharField(default='', max_length=256, verbose_name='발행 키워드')),
                ('transmission_url_date', models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 작성일')),
                ('transmission_url_views', models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 조회수')),
                ('transmission_url_comment_cnt', models.CharField(default='', max_length=256, verbose_name='송출된 URL 상세 조회수')),
                ('pc_views', models.CharField(default='', max_length=256, verbose_name='조회수(PC)')),
                ('mobile_views', models.CharField(default='', max_length=256, verbose_name='조회수(Mobile)')),
                ('area_ranking', models.IntegerField(default=0, verbose_name='영역 순위')),
                ('ranking', models.IntegerField(default=0, verbose_name='순위')),
                ('name', models.CharField(default='', max_length=256, verbose_name='ID(답변인 이름)')),
                ('is_transmission', models.BooleanField(default=False, verbose_name='송출 유무')),
                ('question_date', models.CharField(default='', max_length=256, verbose_name='질문일자')),
                ('type', models.CharField(default='', max_length=256, verbose_name='종류')),
                ('is_subkeyword', models.BooleanField(default=False, verbose_name='서브키워드 유무')),
            ],
            options={
                'verbose_name': '일일 결과',
                'db_table': 'test_daily_result',
            },
        ),
    ]
