# Generated by Django 4.1.2 on 2024-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_testtdailyresult'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyresult',
            index=models.Index(fields=['created_dt'], name='daily_resul_created_c368cc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyresult',
            index=models.Index(fields=['question_date'], name='daily_resul_questio_3fa58f_idx'),
        ),
    ]
