# Generated by Django 4.1.2 on 2024-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_dailyresult_daily_resul_created_c368cc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAndKeychalStandardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('url', models.CharField(default='', max_length=256, verbose_name='url')),
                ('type', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name': '블로그 키챌 기준정보 키워드',
                'db_table': 'blog_and_keychal_standard_information',
            },
        ),
    ]
