# Generated by Django 4.1.2 on 2024-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_blogandkeychalstandardinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAreaStandardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
            ],
            options={
                'verbose_name': '통검 기준정보 키워드',
                'db_table': 'integration_area_standard_information',
            },
        ),
        migrations.CreateModel(
            name='ViewsStandardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
            ],
            options={
                'verbose_name': '조회수 기준정보 키워드',
                'db_table': 'views_standard_information',
            },
        ),
    ]
