# Generated by Django 4.1.2 on 2024-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_integrationareastandardinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogandkeychalstandardinformation',
            name='category',
            field=models.CharField(default='', max_length=256, verbose_name='유형'),
        ),
    ]
