# Generated by Django 4.1.2 on 2024-06-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_blogandkeychalstandardinformation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogandkeychalstandardinformation',
            name='url',
            field=models.CharField(default='', max_length=1024, verbose_name='url'),
        ),
    ]
