# Generated by Django 4.1.2 on 2025-08-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_inurldetailviewcounter_answer_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockIP',
        ),
        migrations.DeleteModel(
            name='BlogAndKeychalStandardInformation',
        ),
        migrations.DeleteModel(
            name='CheckCollection',
        ),
        migrations.DeleteModel(
            name='IntegrationAreaStandardInformation',
        ),
        migrations.DeleteModel(
            name='INURLDetailViewCounter',
        ),
        migrations.DeleteModel(
            name='LastProcessedIndex',
        ),
        migrations.DeleteModel(
            name='TesttDailyResult',
        ),
        migrations.DeleteModel(
            name='ViewsStandardInformation',
        ),
    ]
