# Generated by Django 4.1.2 on 2025-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_delete_blockip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INURLDetailViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('product', models.CharField(default='', max_length=256, verbose_name='제품')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('url', models.CharField(default='', max_length=256, verbose_name='URL')),
            ],
            options={
                'verbose_name': '지식인 조회수',
                'db_table': 'in_url_detail_view_counter',
            },
        ),
    ]
