# Generated by Django 4.1.2 on 2025-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_inurldetailviewcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='inurldetailviewcounter',
            name='answer_code',
            field=models.CharField(default='', max_length=256, verbose_name='답변코드'),
        ),
    ]
